#%RAML 1.0 NamedExample
{
  errorcode: '0001',
  errortype: 'APPERROR:CLIENT_ALREADY_EXISTS',
  errormessage: 'The client with ID: test1 is already registered',
  msgtype: 'register',
  exceptiontype: 'system'
}