#%RAML 1.0
title: estoreexpress-errorapi-mule

uses:
  apiLib: datatypes/apilib.raml

/ping:
  get:
    description: ping
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/test1.raml
/createerror:
  post:
    description: createerror
    body:
        application/json:
          type:  apiLib.createerror
          example: |
            {
              "errorcode": "0001",
              "errortype": "APPERROR:CLIENT_ALREADY_EXISTS",
              "errormessage": "The client with ID: test1 is already registered",
              "msgtype": "register",
              "exceptiontype": "system"              
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/createerror.raml
/readerror:
  get:
    description: readerror
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/readerror.raml
/createerrorbulk:
  post:
    description: createerrorbulk
    body:
        application/json:
          type:  apiLib.createerror[]
          example: |
            [{
              "errorcode": "0001",
              "errortype": "APPERROR:CLIENT_ALREADY_EXISTS",
              "errormessage": "The client with ID: test1 is already registered",
              "msgtype": "register",
              "exceptiontype": "system"              
            }]
    responses:
      200:
        body:
          application/json:
            type: array
            examples:
              example1: !include examples/createerrorbulk.raml
/createerrorfile:
  post:
    description: createerror
    body:
        application/json:
          type:  apiLib.createerror
          example: |
            {
              "errorcode": "0001",
              "errortype": "APPERROR:CLIENT_ALREADY_EXISTS",
              "errormessage": "The client with ID: test1 is already registered",
              "msgtype": "register",
              "exceptiontype": "system"              
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/createerror.raml
/createerrorfilebulk:
  post:
    description: createerrorbulk
    body:
        application/json:
          type:  apiLib.createerror[]
          example: |
            [{
              "errorcode": "0001",
              "errortype": "APPERROR:CLIENT_ALREADY_EXISTS",
              "errormessage": "The client with ID: test1 is already registered",
              "msgtype": "register",
              "exceptiontype": "system"              
            }]
    responses:
      200:
        body:
          application/json:
            type: array
            examples:
              example1: !include examples/createerrorbulk.raml
